export const FORM_SUBMIT = 'FORM_SUBMIT';
//VALIDATE
export const VALIDATE_EMAIL = 'VALIDATE_EMAIL';
export const VALIDATE_LOGIN = 'VALIDATE_LOGIN';
export const VALIDATE_PASSWORD = 'VALIDATE_PASSWORD';
//SERVER
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE';
